### ISSUE TITLE
Exception while running the Dresden Scenario

### ISSUE THREAD

**Issue by abhisheksena** [matsim-org/matsim-episim-libs#84]
While trying to run `--modules SnzDresdenScenario --iterations 10` scenario got the following error:

```com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at org.matsim.run.modules.SnzDresdenScenario.config(SnzDresdenScenario.java:74) (via modules: com.google.inject.util.Modules$OverrideModule -> org.matsim.run.modules.SnzDresdenScenario)
  while locating org.matsim.core.config.Config

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at org.matsim.run.RunEpisim.call(RunEpisim.java:243)
	at org.matsim.run.RunEpisim.call(RunEpisim.java:63)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at org.matsim.run.RunEpisim.main(RunEpisim.java:120)
Caused by: java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$6$1.accept(ReferencePipeline.java:246)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.DoublePipeline.collect(DoublePipeline.java:514)
	at java.base/java.util.stream.DoublePipeline.average(DoublePipeline.java:467)
	at org.matsim.episim.model.input.CreateRestrictionsFromCSV.createPolicy(CreateRestrictionsFromCSV.java:115)
	at org.matsim.run.modules.SnzBerlinScenario25pct2020.basePolicy(SnzBerlinScenario25pct2020.java:67)
	at org.matsim.run.modules.SnzBerlinScenario25pct2020$BasePolicyBuilder.build(SnzBerlinScenario25pct2020.java:266)
	at org.matsim.run.modules.SnzDresdenScenario.config(SnzDresdenScenario.java:159)
	at org.matsim.run.modules.SnzDresdenScenario$$FastClassByGuice$$1512a4f9.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 11 more
```

**Comment by rakow** [comment]
I could not reproduce the error with the version on the develop branch. It looks like this error is related to the restriction csv file. Maybe you did some modifications or something is wrong with the file?

**Comment by elect86** [comment]
Hey @rakow ,

I'm supporting @abhisheksena trying to get this running.

Let's first try to address the data integrity, these are the md5 checksums:

```
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml 
9ceb4d8f38a36d5004b13d512d593c42  dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_sa_100pt_split.xml 
47ee861ec96337ae73b294bedb2ac6b0  dresden_snz_episim_events_sa_100pt_split.xml
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_so_100pt_split.xml 
8f644aa2824d68bf2376797b2c504f3d  dresden_snz_episim_events_so_100pt_split.xml
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_wt_100pt_split.xml 
0fa0fadecdf3a909066fb10be825b023  dresden_snz_episim_events_wt_100pt_split.xml
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum DresdenSnzData_daily_until20210531.csv 
2ab2a6bbad0b13964dbcaa62e68731fe  DresdenSnzData_daily_until20210531.csv
```

Can you double check if those corresponds on your machine?

**Comment by rakow** [comment]
It seems you decompressed all the .gz files. This is not necessary to run the simulation. Could you send me the hashes of the unmodified files? Thanks

**Comment by elect86** [comment]
Sure

```
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum DresdenSnzData_daily_until20210531.csv.gz 
837c0cc8027c66cab296823049c66317  DresdenSnzData_daily_until20210531.csv.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml.gz 
b989c28b47654bab06a99e4f2c493b52  dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_sa_100pt_split.xml.gz 
971a3926adc3f61031adf7eba13bf66b  dresden_snz_episim_events_sa_100pt_split.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_so_100pt_split.xml.gz 
ac5fbdc4a0c6566358ef875662f3e1f2  dresden_snz_episim_events_so_100pt_split.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_wt_100pt_split.xml.gz 
86300dc47be2d9a23770115ed4bd8198  dresden_snz_episim_events_wt_100pt_split.xml.gz
```

**Comment by rakow** [comment]
The `DresdenSnzData_daily_until20210531.csv` should not have been compressed originally. My hashes don't match at all. It looks a bit like you recompressed them. Please download them again and make sure they don't get decompressed automatically, thanks.

**Comment by elect86** [comment]
Indeed, I got them uncompressed and then I compressed them back

These are the new hashes

```
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml.gz 
2b19388868849630947f2802dfd8cd38  dresden_snz_entirePopulation_emptyPlans_withDistricts_100pt_split_noCoord.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_sa_100pt_split.xml.gz 
ee5a51284d78b1362aa5214347041780  dresden_snz_episim_events_sa_100pt_split.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_so_100pt_split.xml.gz 
9ea736975b53102d30e163989e8bba39  dresden_snz_episim_events_so_100pt_split.xml.gz
elect@5800x:~/IdeaProjects/matsim-episim-libs/dresden$ md5sum dresden_snz_episim_events_wt_100pt_split.xml.gz 
ec43cf4eb22b0bed74f0fcb887286b98  dresden_snz_episim_events_wt_100pt_split.xml.gz
```

The file exception remains though

**Comment by rakow** [comment]
Resolved during meeting

**Comment by elect86** [comment]
Btw, after a fresh re-clone and re-download of dresden files, `master` keeps failing, `develop` works fine
